### ISSUE TITLE
Consider adding a global confirm parameter

### ISSUE THREAD

**Issue by pascalduez** [KillianKemps/Git-Repo-Update#1]
Greetings @KillianKemps :)

Would that be an option to add a global parameter, for cases where you want to reply `yes` to all repos anyway ? Provided you know what your doing.

**Comment by KillianKemps** [comment]
Hey @pascalduez ! ;)

You mean something like `./upgrade --force-yes` and `./upgrade -f`?

Yes it is not a bad idea, I will consider adding this parameter

**Comment by pascalduez** [comment]
:+1:
